services:
  - type: web
    name: Resurs_platform
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    autoDeployTrigger: commit
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: UPLOAD_DIR
        value: uploads
      - key: FRONTEND_URL
        value: https://resurs-platform.onrender.com
      - key: BACKEND_URL
        value: https://resurs-platform.onrender.com
      - key: BOOTSTRAP_ADMIN_NAME
        sync: false
      - key: BOOTSTRAP_ADMIN_EMAIL
        sync: false
      - key: BOOTSTRAP_ADMIN_PASSWORD
        sync: false
